// Zero-dependency HTML document model: parse (validate) -> mutate -> serialize.
// The design draft IS the HTML file: nodes are elements with data-cf-id,
// types are data-cf-type, props are data-* attributes on the node root.
// Chrome (toolbar/stage/canvas/fig labels/zoombar) is framework-owned and
// regenerated by serialize, so the file always stays readable and valid.
// Specs: design_harness_html_document, design_harness_http_mcp
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { randomUUID } from 'node:crypto';
import { renderNode, validateType, validateProps, canHaveChildren } from './components.js';

const REFERENCE_DIR = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../../reference');
const SHARED_CSS = fs.readFileSync(path.join(REFERENCE_DIR, 'canvas-frames.css'), 'utf8');
const SHARED_JS = fs.readFileSync(path.join(REFERENCE_DIR, 'canvas-frames.js'), 'utf8');

export function newId(prefix) {
  return (prefix || 'n') + '_' + randomUUID().slice(0, 8);
}

function esc(value) {
  return String(value ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;');
}

const VOID_TAGS = new Set(['br', 'img', 'hr', 'input', 'meta', 'link']);

function parseAttrsText(text) {
  const attrs = {};
  const re = /([a-zA-Z_:][-a-zA-Z0-9_:.]*)(?:\s*=\s*"([^"]*)")?/g;
  let match;
  let last = 0;
  while ((match = re.exec(text))) {
    if (match.index > last && /\S/.test(text.slice(last, match.index))) {
      throw new Error('malformed attribute list');
    }
    if (Object.prototype.hasOwnProperty.call(attrs, match[1])) {
      throw new Error(`duplicate attribute: ${match[1]}`);
    }
    attrs[match[1]] = match[2] === undefined ? '' : decodeEntities(match[2]);
    last = re.lastIndex;
  }
  if (last < text.length && /\S/.test(text.slice(last))) {
    throw new Error('malformed attribute list');
  }
  return attrs;
}

function decodeEntities(text) {
  return text
    .replace(/&quot;/g, '"')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&amp;/g, '&');
}

// Parses the content zone of a harness HTML file into a document model.
// Only elements with data-cf-id become nodes; everything else is chrome.
export function parseDocument(source) {
  const rootMatch = source.match(/<div[^>]*id="canvas-frames-demo"[^>]*>/);
  if (!rootMatch) throw new Error('missing canvas-frames-demo root');
  const scriptAt = source.indexOf('<script>', rootMatch.index);
  if (scriptAt < 0) throw new Error('missing inline script');
  const zone = source.slice(rootMatch.index, scriptAt);

  const ids = new Set();
  const title = (source.match(/<title>([^<]*)<\/title>/) || [])[1] || 'untitled';
  const slug = title.toLowerCase().replace(/[^a-z0-9]+/g, '_').replace(/^_+|_+$/g, '').slice(0, 24) || 'doc';
  const doc = { id: `doc_${slug}`, name: title, pages: [] };
  const tagStack = []; // {name, node|null}
  const nodeStack = []; // nodes with data-cf-id awaiting children
  let pos = 0;

  while (pos < zone.length) {
    const open = zone.indexOf('<', pos);
    if (open < 0) break;
    if (zone.startsWith('<!--', open)) {
      const close = zone.indexOf('-->', open + 4);
      if (close < 0) throw new Error('unclosed comment');
      pos = close + 3;
      continue;
    }
    const closeTag = zone.startsWith('</', open);
    const gt = zone.indexOf('>', open);
    if (gt < 0) throw new Error('unclosed tag');
    const inner = zone.slice(open + (closeTag ? 2 : 1), gt).trim();
    const nameMatch = inner.match(/^[a-zA-Z][a-zA-Z0-9]*/);
    if (!nameMatch) throw new Error('malformed tag');
    const name = nameMatch[0].toLowerCase();
    pos = gt + 1;

    if (closeTag) {
      const top = tagStack.pop();
      if (!top || top.name !== name) {
        throw new Error(`mismatched closing tag </${name}> (expected </${top?.name || 'none'}>)`);
      }
      if (top.node && nodeStack[nodeStack.length - 1] === top.node) {
        nodeStack.pop();
      }
      continue;
    }

    const raw = zone.slice(open + 1, gt);
    const selfClosing = /\/\s*$/.test(raw);
    const clean = selfClosing ? raw.replace(/\/\s*$/, '') : raw;
    const attrs = parseAttrsText(clean.slice(name.length));
    pos = gt + 1;
    if (VOID_TAGS.has(name) || selfClosing) continue;

    let node = null;
    const rawId = attrs['data-cf-id'];
    if (rawId) {
      if (ids.has(rawId)) throw new Error(`duplicate data-cf-id: ${rawId}`);
      ids.add(rawId);
      node = nodeFromAttrs(rawId, attrs);
      const parentNode = nodeStack[nodeStack.length - 1] || null;
      if (parentNode && parentNode.type === 'frame') {
        parentNode.components.push(node);
      } else if (parentNode && parentNode.type === 'page' && node.type === 'frame') {
        parentNode.frames.push(node);
      } else if (parentNode) {
        const list = parentNode.components || parentNode.children;
        list.push(node);
      } else if (node.type === 'page') {
        doc.pages.push(node);
      } else {
        throw new Error(`node ${rawId} (${node.type}) must live under a page`);
      }
      if (canHaveChildren(node.type)) nodeStack.push(node);
    }
    tagStack.push({ name, node });
  }

  if (tagStack.length > 0) {
    throw new Error(`unclosed tags: ${tagStack.map((t) => t.name).join(', ')}`);
  }
  return doc;
}

function nodeFromAttrs(id, attrs) {
  const type = attrs['data-cf-type'];
  const typeError = validateType(type);
  if (typeError) throw new Error(`${typeError} (node ${id})`);
  const props = {};
  for (const [key, value] of Object.entries(attrs)) {
    if (key === 'data-cf-id' || key === 'data-cf-type' || key === 'class' || key === 'style') continue;
    if (!key.startsWith('data-')) continue;
    const prop = key.slice(5);
    let parsed = value;
    if (parsed === 'true') parsed = true;
    else if (parsed === 'false') parsed = false;
    else if (/^-?\d+(\.\d+)?$/.test(parsed)) parsed = Number(parsed);
    else if (parsed.startsWith('[') || parsed.startsWith('{')) {
      try { parsed = JSON.parse(parsed); } catch { /* keep string */ }
    }
    props[prop] = parsed;
  }
  if (type === 'page') return { id, type, props, frames: [] };
  if (type === 'frame') {
    return {
      id,
      type,
      props: {
        name: props.name ?? '',
        kind: props.kind ?? 'phone',
        size: { w: Number(props.w ?? 393), h: Number(props.h ?? 852) },
      },
      components: [],
    };
  }
  const error = validateProps(type, props);
  if (error) throw new Error(`${error} (node ${id})`);
  return { id, type, props, children: [] };
}

export function findNode(doc, nodeId) {
  for (const page of doc.pages) {
    for (const frame of page.frames) {
      const found = findInTree(frame, nodeId);
      if (found) return found;
    }
  }
  return null;
}

function findInTree(node, nodeId) {
  if (node.id === nodeId) return node;
  for (const child of node.children || node.components || []) {
    const found = findInTree(child, nodeId);
    if (found) return found;
  }
  return null;
}

export function findFrame(doc, frameId) {
  for (const page of doc.pages) {
    const frame = page.frames.find((item) => item.id === frameId);
    if (frame) return frame;
  }
  return null;
}

export function findPage(doc, pageId) {
  return doc.pages.find((page) => page.id === pageId);
}

function renderFrame(frame) {
  const components = (frame.components || []).map(renderNode).join('\n');
  return `<div class="cf-frame" data-cf-id="${frame.id}" data-cf-type="frame" data-name="${esc(frame.props.name)}" data-kind="${esc(frame.props.kind)}" data-w="${frame.props.size.w}" data-h="${frame.props.size.h}" role="img">\n${components}\n</div>`;
}

function renderPage(page) {
  const frames = (page.frames || [])
    .map(
      (frame) => `<div class="cf-fig">
            <div class="cf-fig-label">
              <span class="cf-fr-badge"></span><b>${esc(page.props.name)}</b>
              <span>${esc(frame.props.name)}</span><span class="cf-dims">${frame.props.size.w} × ${frame.props.size.h}</span>
            </div>
            <div class="cf-frame-wrap">${renderFrame(frame)}</div>
          </div>`,
    )
    .join('\n');
  return `<div class="cf-page" data-cf-id="${page.id}" data-cf-type="page" data-name="${esc(page.props.name)}" data-page="${page.id}">
    <div class="cf-stage">
      <div class="cf-canvas-viewport">
        <div class="cf-canvas-inner">
          <div class="cf-canvas">
${frames}
          </div>
        </div>
      </div>
      <div class="cf-zoombar">
        <button type="button" data-zoom="out" aria-label="缩小">−</button>
        <span class="cf-zoom-value">100%</span>
        <button type="button" data-zoom="in" aria-label="放大">+</button>
        <button type="button" class="cf-zoom-fit" data-zoom="fit">适应</button>
      </div>
    </div>
  </div>`;
}

// Deterministic model -> readable standalone HTML. The same model always
// produces the same document; chrome is regenerated, node data is preserved.
export function serializeDocument(doc) {
  const tabs = doc.pages
    .map((page) => `<button class="cf-pagetab" role="tab">${esc(page.props.name)}</button>`)
    .join('\n');
  const pages = doc.pages.map(renderPage).join('\n');
  return `<!doctype html>
<html lang="zh-CN">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${esc(doc.name)}</title>
<style>${SHARED_CSS}
body{margin:0;padding:14px;background:#f4f6f8}
</style>
</head>
<body>
<div id="canvas-frames-demo">
<div class="cf-toolbar">
  <span class="cf-toolbar-title">${esc(doc.name)}</span>
  <div class="cf-pagetabs" role="tablist" aria-label="选择页面">
${tabs}
  </div>
</div>
${pages}
</div>
<script>${SHARED_JS}</script>
</body>
</html>
`;
}

export function emptyDocument(name) {
  // create_file yields an empty document; pages are created explicitly by
  // the agent (document.createPage), so a journey never gains a stray page.
  return { id: newId('doc'), name: name || 'untitled', pages: [] };
}
