// scripts/build-client.mjs — assemble client/bundle.js from client/design-view.js.
//
// The DSH web shell (dsh-client-modules + dsh-client-web) loads client bundles
// as classic scripts that register a factory via
// window.__ModuleLoader__.load({ id, factory }). The factory body receives a
// require() whose only resolvable specifiers are the platform static module
// table (react, react/jsx-runtime, react-dom, @deepseek-ai/cordis,
// @deepseek-ai/dsh-client-ui-slots, @deepseek-ai/dsh-client-web-react,
// @deepseek-ai/dsh-client-ui-primitives, ...) plus registered bundle ids —
// see getStaticModules() in @deepseek-ai/dsh-client-web. This wrapper injects
// the shell's React instance and exports the cordis plugin face ({inject,
// apply}), so the bundle body itself never imports anything.
import { readFileSync, writeFileSync } from "node:fs";

const body = readFileSync(new URL("../client/design-view.js", import.meta.url), "utf8");
const header = "// GENERATED by scripts/build-client.mjs from client/design-view.js — do not edit by hand.\n";
const bundle =
  header +
  'window.__ModuleLoader__.load({\n' +
  '\tid: "dsh-canvas-design-harness",\n' +
  '\tfactory: (require) => {\n' +
  '\t\tvar module = { exports: {} };\n' +
  '\t\tvar exports = module.exports;\n' +
  '\t\tvar React = require("react");\n' +
  body +
  '\n\t\texports.apply = apply;\n' +
  '\t\texports.inject = inject;\n' +
  '\t\treturn module.exports;\n' +
  '\t}\n' +
  '});\n';

writeFileSync(new URL("../client/bundle.js", import.meta.url), bundle);
console.log("client/bundle.js written (" + bundle.length + " bytes)");
